const express = require('express')
const router = express.Router()
const controlador = require('./controlador')

router.post('/crear_servicio',controlador.crearServicio)
router.post('/crear_servicio_otros',controlador.crearServicioOtros)
router.get('/ver_servicio/:id',controlador.verServicio)
router.get('/ver_servicio_otros/:id',controlador.verServicioOtros)
router.get('/ver_servicios_cliente/:id_cliente/:estado',controlador.verServiciosPorClienteId)
router.put('/cambiar_estado_servicio/:id',controlador.cambiarEstadoServicio)
router.post('/crear_linea_servicio',controlador.crearLineaServicio)
router.put('/editar_linea_servicio/:id_linea_servicio',controlador.editarLineaServicio)
router.delete('/eliminar_linea_servicio/:id_linea_servicio',controlador.eliminarLineaServicio)
router.post('/crear_pago',controlador.crearPago)
router.put('/editar_pago/:id_pago',controlador.editarPago)
router.delete('/eliminar_pago/:id_pago',controlador.eliminarPago)
router.get('/obtener_pagos/:id_linea_servicio',controlador.obtenerPagos)
router.get('/obtener_vehiculos_asociados/:id_chofer',controlador.obtenerVehiculosAsociadosChoferId)
router.post('/crear_ingreso',controlador.crearIngreso)
router.delete('/eliminar_ingreso/:id_ingreso',controlador.eliminarIngreso)

module.exports = router